### ISSUE TITLE
ptr_vector::c_array is not compiling when boost::nullable is used in ptr_vector.

### ISSUE THREAD

**Issue by moose-x86** [boostorg/ptr_container#14]
Hi,

using c_array is not possible if boost::ptr_vector<boost::nullable<int>>.
Compile error is that "can not convert boost::nullable<int>** to int**."

Br,
Przemek

https://github.com/boostorg/ptr_container/blob/17c3d7ce79ca1756d1ab13c7f315cb90a51cd43f/include/boost/ptr_container/ptr_sequence_adapter.hpp#L539

**Comment by eldiener** [comment]
Please show a minimum code example where the compile error occurs.
